config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'
  get 'pricing', to: "home#pricing"
  resources :maps
  resources :layouts
  resources :players do
    get 'token'
  end
  get 'maps/:map_code/load', to: "players#load"
  get 'maps/:map_code/:player_code', to: "players#load"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/layout.rb
class Layout < ApplicationRecord
  belongs_to :map
end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :default_layout, class_name: 'Layout', foreign_key: 'default_layout_id', optional: true
  belongs_to :user
  has_many :layouts
  has_many :players

  mount_uploader :preview, PreviewUploader

  def cookie_auth_token
    "map_#{self.access_code}_authorization"
  end

  def preview_filename
    "#{self.id}_#{self.access_code}_preview.svg"
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :map

  validates_exclusion_of :code, :in => %w(load),
      :message => 'Player code "%{value}" is reserved.'
  validates_uniqueness_of :code, :scope => :map,
    :message => 'Player code "%{value}" is already in use for this map'
  validates_uniqueness_of :token_label, :scope => :map,
    :message => 'Token label "%{value}" is already in use for this map'
  validates :token_label, length: { maximum: 2 }
  validates :token_color, length: { is: 6 }
  validates :code, :token_label, :token_color, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  has_many :maps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    maps_path
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/caf_controller.rb
class CafController < ApplicationController

  def index
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'marketing', :except => [:pricing]
  def index
    if user_signed_in?
      @cta_path = maps_path
    else
      @cta_path = new_registration_path(User)
    end
  end

  def pricing
  end
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  before_action :authenticate_user!

  def create
    @map = Map.find(params[:map])
    @layout = Layout.new(secure_params)
    @layout.update_attributes(grid: {}, map: @map)
    @layout.save
    render :json => @layout
  end

  def update
    @layout = Layout.find_by_id(params[:id])
    if @layout.update_attributes(secure_params)
      render :json => { success: true }
    else
      render :json => { success: false }
    end
  end

  private

  def secure_params
    params.require(:layout).permit(:name)
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :authenticate_user!, :except => [:show]

  def index
  end

  def show
    # If the id is numeric, this is a direct map load. Otherwise it is an access code
    if params[:id].match(/\A[0-9]+\Z/)
      show_map(params)
    else
      show_auth_player(params)
    end
  end

  def new
    @map = Map.new
  end

  def create
    attributes = secure_params
    attributes[:access_code] = generate_token
    @map = Map.new(attributes)

    @layout = Layout.create(
      name: 'Untitled',
      map: @map,
      height: 15,
      width: 15,
      grid: {}
    )

    @map.update(default_layout: @layout, user: current_user)
    @layout.save
    @map.save
    flash[:notice] = "Created #{@map.name}"
    redirect_to map_path(@map)

    GeneratePreviewWorker.perform_async(@map.id)
  end

  def update
    @map = Map.find_by_id(params[:id])
    attrs = secure_params

    if @map.update_attributes(attrs)
      render :json => { success: true }

      if attrs.include?(:default_layout_id)
        GeneratePreviewWorker.perform_async(@map.id)
      end
    else
      render :json => { success: false }
    end
  end

  private

  def show_map(params)
    authenticate_user!
    @map = Map.find_by_id(params[:id])

    if map_admin?(@map)
      @player_id = 'dm'
      respond_to do |format|
        format.json { render :json => @map, :include => ['layouts', 'players'] }
        format.html { render :template => "maps/show_map", :layout => "map" }
      end
    elsif session[@map.cookie_auth_token]
      respond_to do |format|
        format.json { render :json => @map, :include => ['layouts', 'players'] }
        format.html { not_found }
      end
    else
      not_found
    end
  end

  def show_auth_player(params)
    @map = Map.where(access_code: params[:id]).first
    @new_player = Player.new
    respond_to do |format|
      format.json { render :json => @map, :include => 'layouts' }
      format.html { render :template => "maps/auth_player" }
    end
  end

  def map_admin?(map)
    @map.user == current_user || ENV['ADMIN_EMAILS'].split(' ').include?(current_user.email)
  end

  def secure_params
    params.require(:map).permit(:name, :default_layout_id)
  end

  def generate_token
    loop do
      random_token = SecureRandom.alphanumeric(5).downcase
      break random_token unless Map.exists?(access_code: random_token)
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  layout false
  layout 'application', :except => :token
  layout "map", :only => [:load]

  def load
    if !params[:player_code]
      redirect_to "/maps/#{map.access_code}"
    else
      @map = Map.where(access_code: params[:map_code]).first

      if !@map
        # This is not the right thing to do, really...
        redirect_to "/maps/#{params[:map_code]}"
        return
      end

      @player = Player.where(map: @map, code: params[:player_code]).first

      if !@player
        redirect_to "/maps/#{params[:map_code]}", flash: { load_errors: ["Access code not found"] }
        return
      end

      session[@map.cookie_auth_token] = true
      session[:player_token] ||= "#{@player.code}_#{@map.access_code}"

      @player_id = @player.id
      render :template => "maps/show_map"
    end
  end

  def create
    map = Map.find_by_id(params[:player][:map])

    @player = Player.create(secure_params)
    @player.map = map
    @player.save

    if !@player.valid?
      redirect_to "/maps/#{map.access_code}", flash: { create_errors: @player.errors.full_messages }
    else
      UserMailer.with({
        user: map.user,
        player: @player,
        map: map
      }).new_player_email.deliver_later
      redirect_to "/maps/#{map.access_code}/#{@player.code}"
    end
  end

  def token
    @player = Player.find_by_id(params['player_id'])

    if !@player
      not_found
    end

    respond_to do |format|
      format.svg { render :template => "players/token" }
      format.png {
        rendered = render_to_string(:template => "players/token.svg")
        img, data = Magick::Image.from_blob(rendered) {
          self.format = 'SVG'
          self.background_color = 'transparent'
          self.size = "86.6x100"
        }

        blob = img.to_blob {
          self.format = 'PNG'
        }
        send_data blob, :type => "image/png", :disposition => "inline"
      }
    end
  end

  private

  def secure_params
    sec = params.require(:player).permit(
      :code,
      :token_color,
      :token_label
    )

    if sec.has_key?(:token_color) && sec[:token_color][0] = '#'
      sec[:token_color] = sec[:token_color].slice(1, 6)
    end

    return sec
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% content_for :head_tags do %>
  <%= stylesheet_link_tag 'home', media: 'all' %>
<% end %>

<div class="hero">
  <div class="hero-bg">
    <%= image_tag "welton-bg.png", class: "w50" %>
    <%= image_tag "welton.gif", class: "w50", style: "position: absolute; top: 0; left: 0;" %>
  </div>
  <div class="hero-text">
    <div class="p tc">
      <%= image_tag "logo.png", class: "w-5" %>
      <h1 class="white f5 vt p-l mb-b fw1">MakeHex</h1>
      <h2 class="darkWhite fw1 f3">Easy hex maps for tabletop gaming</h2>
      <%= link_to "Make a Map", @cta_path, class: "button dib wa green pb-x f3 m-t" %>
    </div>
  </div>
</div>

<div class="features flex around pb-b">
  <div>
    <div class="hexagon">
      <%= image_tag "easymaps.png" %>
    </div>
    <h3 class="tc mb-t p-t">Maps Made Easy</h3>
    <p class="mauto w75">Anyone can run a tabletop game - creative skills are optional. Low-fidelity hex maps allow you to focus on your story-telling while giving players a tactical tool.</p>
  </div>
  <div>
    <div class="hexagon">
      <%= image_tag "anywhere.png" %>
    </div>
    <h3 class="tc mb-t p-t">Play Anywhere</h3>
    <p class="mauto w75">Whether your party meets in-person or virtually, the best gaming happens when players are comfortably controlling their own devices.</p>
  </div>
  <div>
    <div class="hexagon">
      <%= image_tag "livegaming.png" %>
    </div>
    <h3 class="tc mb-t p-t">Live Gaming</h3>
    <p class="mauto w75">Build an immersive encounter with live-updating maps that both you and your players can interact with in real-time.</p>
  </div>
</div>

<div class="southport">
  <div></div>
</div>

<div class="oss tc">
  <h3 class="f5 fw2">MakeHex is Open Source!</h3>
  <p><a href="https://github.com/josephwegner/makehex" class="button grey">Contribute</a> or <a href="https://www.patreon.com/makednd" class="button">Donate</a></p>
</div>

<div class="footer tc">
  <%= link_to "Make a Map", @cta_path, class: "button dib wa green pb-x f4 m-t" %>
  <p class="f3 p-t m0-b">Made with <i class="red">&#x2764;</i> and open source. Chat us up in <a href="https://discord.gg/VTWF3GG">Discord</a>.</p>
  <p class="lightGray f3 p-b ms-t"><a href="https://simpleanalytics.io/makehex.com">Privacy-friendly Analytics</a> via Simple Analytics - use <a href="https://referral.simpleanalytics.com/joe">this link</a> for a free month.</a></p>
</div>

app/views/home/pricing.html.erb
<% content_for :head_tags do %>
  <%= stylesheet_link_tag 'home', media: 'all' %>
<% end %>
<div id="nav">
  <%= link_to "Pricing", pricing_path %>
  <%= link_to "Log in →", new_session_path(User) %>
</div>

<p class="white mauto f3 fw1 bg-darkGray mb-t p" style="max-width: 50rem; border-radius: var(--borderRadius);">
MakeHex is an open-source project, which for now at least means I pretty much do with it what I want and build the parts that are most interesting to me. Pricing is annoying and scary for me, so I've procrastinated on it. It's on my todo list, and something I'll have to do soon, but not yet. In the mean time, if you create an account you'll be grandfathered into free "premium" (wtv that means) forever. That obviously won't be the case once I convince myself to build the billing stuff.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MakeHex</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'outofapp', media: 'all' %>
    <%= render :partial => 'shared/social_tags' %>

    <%= yield :head_tags %>
  </head>

  <body>
    <%= render :partial => "shared/header" %>
    <%= render :partial => "shared/submenu" if content_for?(:submenu) %>
    <% if !flash.empty? %>
      <div class="flash bg-blue tc white p">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg %>
        <% end %>
      </div>
    <% end %>
    <%= yield %>
    <%= javascript_pack_tag 'outofapp', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/layouts/map.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MakeHex</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'vue', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render :partial => 'shared/social_tags' %>

    <%= yield :head_tags %>
  </head>

  <body>
    <%= yield %>
    <svg style="overflow: hidden; top: -100%; left: -100%; position: absolute; opacity: 0;">
      <defs>
        <mask id="fog" maskContentUnits="objectBoundingBox">
          <g transform="rotate(45, .5, .5)" stroke-width="0.2" stroke="#444" >
            <rect fill="#fff" x="0" y="0" width="1" height="1" stroke-width="0" />
            <line x1=".05" y1="0" x2=".05" y2="1" stroke-width=".02" />
            <line x1=".1" y1="0" x2=".1" y2="1" stroke-width=".02" />
            <line x1=".15" y1="0" x2=".15" y2="1" stroke-width=".02" />
            <line x1=".2" y1="0" x2=".2" y2="1" stroke-width=".02" />
            <line x1=".25" y1="0" x2=".25" y2="1" stroke-width=".02" />
            <line x1=".3" y1="0" x2=".3" y2="1" stroke-width=".02" />
            <line x1=".35" y1="0" x2=".35" y2="1" stroke-width=".02" />
            <line x1=".4" y1="0" x2=".4" y2="1" stroke-width=".02" />
            <line x1=".45" y1="0" x2=".45" y2="1" stroke-width=".02" />
            <line x1=".5" y1="0" x2=".5" y2="1" stroke-width=".02" />
            <line x1=".55" y1="0" x2=".55" y2="1" stroke-width=".02" />
            <line x1=".6" y1="0" x2=".6" y2="1" stroke-width=".02" />
            <line x1=".65" y1="0" x2=".65" y2="1" stroke-width=".02" />
            <line x1=".7" y1="0" x2=".7" y2="1" stroke-width=".02" />
            <line x1=".75" y1="0" x2=".75" y2="1" stroke-width=".02" />
            <line x1=".8" y1="0" x2=".8" y2="1" stroke-width=".02" />
            <line x1=".85" y1="0" x2=".85" y2="1" stroke-width=".02" />
            <line x1=".9" y1="0" x2=".9" y2="1" stroke-width=".02" />
            <line x1=".95" y1="0" x2=".95" y2="1" stroke-width=".02" />
          </g>
        </mask>
      </defs>
    </svg>
  </body>
</html>

app/views/layouts/marketing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MakeHex | Easy maps for tabletop gaming</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'outofapp', media: 'all' %>

    <%= render :partial => 'shared/social_tags' %>
    <%= yield :head_tags %>
  </head>
  <body>
    <div id="nav">
      <%= link_to "Pricing", pricing_path %>
      <%= link_to "Log in →", new_session_path(User) %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/transactional_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
    <%= stylesheet_link_tag 'email' %>
  </head>
  <body>
    <div id="container">
      <div id="header">
        <div id="logo-wrap">
          <a href="https://www.makehex.com">
            <%= image_tag 'logo.png', class: 'logo' %>
            <span>MakeHex</span>
          </a>
        </div>
      </div>
      <div id="content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/maps/auth_player.html.erb
<% content_for :head_tags do %>
  <%= stylesheet_link_tag 'outofapp', media: 'all' %>
<% end %>

<div class="centered-form">
  <h2 class="tc">Enter Your Player Code</h2>

  <% if flash[:load_errors] %>
    <% flash[:load_errors].each do |error| %>
      <aside class="error"><%= error %></aside>
    <% end %>
  <% end %>

  <%= form_tag("/maps/#{@map.access_code}/load", method: "get") do |f| %>
    <div class="form-group">
      <%= label_tag :access_code %>
      <%= text_field_tag :player_code, nil, autofocus: true %>
    </div>
    <%= submit_tag "Access Map", :class => "form-submit" %>
  <% end %>

  <h3 class="tc">Or Create a New Player</h3>

  <%= form_for(@new_player) do |f| %>
    <% if flash[:create_errors] %>
      <% flash[:create_errors].each do |error| %>
        <aside class="error"><%= error %></aside>
      <% end %>
    <% end %>
    <%= f.hidden_field :map, value: @map.id %>
    <div class="form-group">
      <%= f.label :access_code %>
      <span class="sublabel">You will use this to access your character in the future.</span>
      <%= f.text_field :code, autofocus: true %>
    </div>
    <div class="form-group inline-form center">
      <div>
        <%= f.label 'Player Label' %>
        <%= f.text_field :token_label, maxlength: 2, size: 2, placeholder: 'MH', style: 'width: 4rem;' %>
      </div>
      <div>
        <%= f.label 'Player Color' %>
        <%= f.color_field :token_color, value: '#297C46', style: 'width: 4rem; height: 2.5rem;' %>
      </div>
    </div>
    <%= f.submit "Create Player", :class => "form-submit" %>
  <% end %>

</div>

app/views/maps/index.html.erb
<% content_for :submenu do %>
  <div class="tr ps-r">
    <%= link_to "New Map", new_map_path, class: "button inline m0" %>
  </div>
<% end %>

<h1>Maps</h1>
<ul class="map-list">
<% current_user.maps.order(created_at: :desc).each do |map| %>
  <li class="map-item">
    <a href="<%= map_path(map.id) %>">
      <% if map.preview.url.nil? %>
        <div class="preview">No Preview</div>
      <% else %>
        <div class="preview" style="background-image: url('<%= map.preview.url %>')"><div></div></div>
      <% end %>
      <div class="details">
        <span class="map-title"><%= map.name %></span>
        <div>
          <span class="sub-detail"><%= map.layouts.count %> layouts</span>
          <span class="sub-detail"><%= map.players.count %> players</span>
        </div>
      </div>
    </a>
  </li>
<% end %>
</ul>

app/views/maps/new.html.erb
<div class="centered-form">
  <%= form_with(model: @map) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <%= f.submit 'Create Map', class: 'form-submit' %>
  <% end %>
</div>

app/views/maps/show_map.html.erb
<% content_for :head_tags do %>
  <%= stylesheet_link_tag 'editor', media: 'all' %>
<% end %>
<svg version="1.1"
     baseProfile="full"
     width="39" height="46"
     xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     style="display: none;">

  <defs>
    <polygon id="hex" points="36.64101615137754,12,36.64101615137754,32 19.32050807568877,42,2,32 2,12,19.32050807568877,2"></polygon>
    <symbol id="arrow-out-right" viewBox="0 0 200 200">
      <path stroke-width="7" d="M40,90
               L120,90
               120,60
               160,100
               120,140
               120,110
               40,110" />
     </symbol>
     <symbol id="arrow-out-right-locked" viewBox="0 0 200 200">
          <path stroke-width="7" d="M40,90
                   L120,90
                    120,60
                    160,100
                    120,140
                    120,110
                    40,110" />
           <rect x="40" y="60" width="60" height="30" />
           <path stroke-width="10" stroke="black" fill="transparent" d="M50 60 a 5 7 0 0 1 40 0" />

     </symbol>

  </defs>
</svg>

<div class="map-root" data-map-id="<%= @map.id %>" data-map-code="<%= @map.access_code %>" data-player="<%= @player_id %>">
  <div class="main-bar">
    <div class="map">

    </div>
  </div>
  <div class="footer-tools">
  </div>
  <div class="toolbar"></div>
</div>

app/views/players/load.html.erb
<span>This will eventually show map
  <%= @map.id %>
  for player
  <%= @player.id %>
</span>

app/views/players/token.svg.erb
<svg version="1.1" id="Layer_1" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns"
	 xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 37 42"
	 style="enable-background:new 0 0 37 42;" xml:space="preserve">
  <polygon id="hex"
          points="36.64101615137754,12,36.64101615137754,32 19.32050807568877,42,2,32 2,12,19.32050807568877,2"
          fill="#<%= @player.token_color %>">
  </polygon>
  <text stroke="#DDD"
        fill="#DDD"
        x="19.5"
        y="27"
				text-anchor="middle">

        <%= @player.token_label %>
  </text>
</svg>

app/views/shared/_header.html.erb
<div class="header p bg-darkGray flex spread">
  <% if user_signed_in?
    path = "/maps"
  else
    path = "/"
  end
  %>
  <a href="<%= path %>" style="text-decoration: none;">
    <%= image_tag 'logo.svg', class: 'w-3 ps-r' %>
    <span class="white f4 vt fw1">MakeHex</span>
  </a>
  <% if user_signed_in? %>
    <%= link_to "Account Settings", edit_user_registration_path, class: 'button inline outline white m0' %>
  <% end %>
</div>

app/views/shared/_social_tags.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge;">
<meta property="og:title" content="Easy maps for tabletop gaming | MakeHex">
<meta name="description" content="Makehex is a hex map tool that enables game masters to create simple immersive maps for their tabletop games.">
<meta property="og:image" content="<%= image_url 'og.png' %>">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Easy maps for tabletop gaming | MakeHex" />
<meta name="twitter:site" content="@JoeWegner">
<meta property="twitter:image" content="<%= image_url 'og.png' %>">
<meta name="twitter:description" content="Makehex is a hex map tool that enables game masters to create simple immersive maps for their tabletop games.">
<link rel="apple-touch-icon-precomposed"
    sizes="57x57" href="<%= image_url 'favicon114.png' %>">
<link rel="apple-touch-icon-precomposed"
    sizes="114x114" href="<%= image_url 'favicon114.png' %>">
<link rel="apple-touch-icon-precomposed"
    sizes="72x72" href="<%= image_url 'favicon144.png' %>">
<link rel="apple-touch-icon-precomposed"
    sizes="144x144" href="<%= image_url 'favicon144.png' %>">
<link rel="shortcut icon" type="image/vnd.microsoft.icon"
    sizes="32x32 48x48" href="<%= image_url 'favicon32.ico' %>">
<link rel="icon" sizes="128x128" href="<%= image_url 'favicon128.icns' %>">
<link rel="icon" href="<%= image_url 'favicon32.png' %>" type="image/x-icon">
<link rel="canonical" href="https://www.makehex.com/">

<script async defer src="https://cdn.simpleanalytics.io/hello.js"></script>
<noscript><img src="https://api.simpleanalytics.io/hello.gif" alt=""></noscript>

app/views/shared/_submenu.html.erb
<div class="submenu bg-gray ps">
  <%= yield :submenu %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>